### PR TITLE
Update upper bounds for `random`

### PR DESCRIPTION
**Pull request by lehins**

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks for this patch! Right now I cannot merge it, because `vty` will not build against `random==1.2.0` because its dependency on `test-framework` also will not build against `random` version `1.2.0`. Once that changes, I can then ensure that `vty` builds successfully with the latest `random`.

**Comment by lehins** [comment]
That's right we need to wait for haskell/test-framework#53 Hopefully someone will get to it soon. It also blocks us from getting random-1.2.0 into stackage commercialhaskell/stackage#5474

**Comment by jtdaugherty** [comment]
Okay, thanks for confirming!

**Comment by lehins** [comment]
haskell/test-framework#53 has been merged, waiting for a revision or new release

**Comment by lehins** [comment]
@jtdaugherty test-framework had a revision added that fixes bounds for random. FYI you didn't have to wait for test-framework to update bounds in order fix the bounds for `vty`. As long as you project works with the newer dependency then it is fine to fix it up front without waiting for transitive dependencies to fix their bounds. Building and checking if it works is possible with `allow-newer` flag.

**Pull request merged**
