### PR TITLE
Specify pkg-config `tinfo` requirement

### PR DESCRIPTION
**Pull request by spacekitteh**

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks for the patch! I'm not sure how this should interact with another unmerged change, though: https://github.com/jtdaugherty/vty/pull/181

**Comment by spacekitteh** [comment]
I could add the flag part; since `tinfo` is a dependency of `ncurses` (as far as I'm aware) then this one actually subsumes that one.

**Comment by jtdaugherty** [comment]
Sorry, my confusion was not about the flag, but about which library should be specified as a dependency. According to the other pull request, the fact that `ncurses` and `tinfo` may be split can cause issues (and I'm not even sure why that patch needed a flag to *disable* `pkg-config`).

Can you say more about the conditions where you encountered the problem that led to this patch? What OS/distribution are you running? Can you provide output from a failing build?

**Comment by spacekitteh** [comment]
I was trying to build a program which uses `vty` as a dependency on a fresh Ubuntu WSL image. I was getting linker errors about not being able to link with "-ltinfo". It took a while to remember that it was trying to find a library `tinfo`, not having trouble with "link-time info".

In other words, the lack of a pkg-config constraint for the `tinfo` library took about an hour to figure out :)

Presumably, the pkg-config settings on distros where they are a single package actually does generate both the `ncurses` and the `tinfo` entries?

**Comment by iphydf** [comment]
tinfo doesn't seem to be a direct requirement anymore?

**Comment by jtdaugherty** [comment]
Closing this due to being stale/no longer needed (for details, see #181).

**Pull request closed without merging**
