### PR TITLE
WIP: Start on Windows support

### PR DESCRIPTION
**Pull request by Invisible-Rabbit-Hunter**
This is my attempt at windows support. Do not merge any time soon. Things will change soon, I just created this pull request to make asking questions about the internals easier, and hopefully eventually have a working build.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks!

Can you help me understand a bit about the approach you have in mind? You mentioned a win32 terminal API. I don't know anything about that - does using that API mean that users would need to use the `cmd.exe` environment to run the Vty program?

**Comment by Invisible-Rabbit-Hunter** [comment]
Win32 has a [console api](https://docs.microsoft.com/en-us/windows/console/console-reference) which allows for things like multiple buffers, cursor positioning, events, etc. I've thought for a while that this would allow for TUIs, but have never heard anyone talk about it. I don't think it locks the user to cmd.exe, as it seems to work with PowerShell too. If the user is using something like Cygwin, it should still work, but I haven't tried it.

I'm planning on writing bindings to the api, and the using them in the windows side of vty.

**Comment by jtdaugherty** [comment]
That's very helpful, thank you!

**Comment by Invisible-Rabbit-Hunter** [comment]
It doesn't seem to work with mintty, so no Cygwin or MSYS.

**Comment by Invisible-Rabbit-Hunter** [comment]
VTY seems to expect the underlying platform to communicate via terminal escape sequences. The windows API I intend to use works by procedures instead. How would I best change the code to allow for procedures instead of escape sequences?

**Comment by jtdaugherty** [comment]
Can you be more specific about the part(s) of the API you're referring to?

**Comment by Invisible-Rabbit-Hunter** [comment]
For example, the `DisplayContext` expects writes, and the whole input part expects input via terminal sequences, both of which windows didn't support until Windows 10.

For output I could probably use `Write`s of size 0, and execute the API calls instead. The biggest problem is that all non-compatible modules are required to be exported in order for the tests to work

**Comment by Supernerd11** [comment]
What encoding does outputByteBuffer expect? Is it utf-8 or dependent on the underlying operating system?

**Comment by Invisible-Rabbit-Hunter** [comment]
Does the `Output` interface's `outputByteBuffer` expect the text to encoded as UTF-8?

**Comment by jtdaugherty** [comment]
It's hard for me to tell; I think for now it's fine to just assume 'yes'.

**Comment by Invisible-Rabbit-Hunter** [comment]
That's a bit frustrating, as Windows loves it's UTF-16, and no has no functions using UTF-8 directly. I'll just have to convert it.

**Comment by jtdaugherty** [comment]
Rather than converting the bytestring, it might be better to push this upstream elsewhere in the API when the `Image`s get converted to bytes. Maybe have the `Output` expose the encoding it prefers, and have that available when the image is converted to bytes.

**Comment by Invisible-Rabbit-Hunter** [comment]
When I look more closely, it seems that encoding happens in the Output.Interface module, via the `text` package, so I can use `encodeUtf16Le` instead of `encodeUtf8` on windows. We can still use bytestrings, but should be more explicit about the encoding.

**Comment by simonmichael** [comment]
Hi @Supernerd11 - just in case it's useful and you hadn't seen it, are you aware of Win32-console ? See https://github.com/jtdaugherty/vty/pull/1#issuecomment-297143444.

**Comment by jtdaugherty** [comment]
I'm closing due to inactivity. Please feel free to re-open if this gets revived!

**Pull request closed without merging**
