### PR TITLE
Make it build with ghc 9.8 (update deps only)

### PR DESCRIPTION
**Pull request by erikd**
Test do not build, but pretty sure that is not due to my changes.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by jtdaugherty** [comment]
The test build is fixed in master, as of a few hours ago.

**Comment by erikd** [comment]
Thanks! Would be great to have a new version on Hackage or better yet a metadata edit on Hackage.

**Comment by jtdaugherty** [comment]
Done!

**Pull request merged**
