### PR TITLE
Raise a VTY specific exception on missing TERM

### LINKED ISSUE #107: Missing TERM leads to crash
If the `TERM` env variable is not set, `vty` leads to a complete crash.  This just happened to me while trying to run a haskell program that uses brick from a docker container missing `TERM`.

The problem is that in https://github.com/coreyoconnor/vty/blob/master/src/Graphics/Vty/Config.hs#L172 there is no fallback of any kind.

### PR DESCRIPTION
**Pull request by glguy**
Fixes #107
Fixes #110

### CODE REVIEW

**Comment by glguy** [comment]
I'll watch the CI to see if this has trouble on older GHCs and provide appropriate fixes as needed

**Comment by glguy** [comment]
The GHC 7.6.3 build failed, but not because of this PR. There was some kind of problem building dlist. I'd be inclined to have the job restarted to see if it would work the second time through. (if you're up for it, @jtdaugherty )

**Comment by jtdaugherty** [comment]
I'm not sure if I have to do anything to kick off another build, but I'm not too worried about that failure (yet).

**Comment by jtdaugherty** [comment]
Thanks!

**Pull request merged**
