### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by ghost**
src/Graphics/Vty/Output.hs
src/Graphics/Vty/Output/TerminfoBased.hs
src/Graphics/Vty/PictureToSpans.hs
test/VerifyImageOps.hs
test/VerifyOutput.hs
test/interactive_terminal_test.hs

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by ghost** [comment]
src/Graphics/Vty/Output/Mock.hs

this line could be edited

`-- sequence of terminal operations matche the expected sequence. The`

**Comment by jtdaugherty** [comment]
Thanks - are you planning to submit a patch? Or shall I fix it?

**Comment by ghost** [comment]
easy either way

but I can submit a patch

**Comment by jtdaugherty** [comment]
In the case above, `matches` would be the replacement.

**Pull request merged**
